
            backup_type = "FullFolder"
            input_path = "/mnt/c/Users/frank/OneDrive/Desktop/App-GemHunter/gemhunter/client/src/icons"
            output_path = "/mnt/c/Users/frank/OneDrive/Desktop"
            